# Generated by Django 5.2.17 on 2026-09-17 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('color', models.CharField(max_length=7)),
                ('partner_house', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='inventory.house')),
            ],
            options={
                'db_table': 'houses',
                'constraints': [models.UniqueConstraint(fields=('name', 'gender'), name='unique_house_name_gender'), models.UniqueConstraint(fields=('code', 'gender'), name='unique_house_code_gender')],
            },
        ),
    ]
