# Generated by Django 5.2.17 on 2026-09-17 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fathers_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mothers_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('residence', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='inventory.house')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['surname', 'firstname', 'created_at'],
            },
        ),
    ]
