# Generated by Django 5.2.17 on 2026-09-17 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='Muhammad', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='house',
            field=models.ForeignKey(default='377427a6-ee03-4aa0-827f-f624a7e9538b', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='inventory.house'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='residence',
            field=models.CharField(default='Accra', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(default='Appiah', max_length=100),
            preserve_default=False,
        ),
    ]
