# Generated by Django 5.2.17 on 2026-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_student_date_of_birth_alter_student_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='student_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
