# Generated by Django 5.2.17 on 2026-09-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_student_is_active_alter_sale_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='student',
            field=models.ForeignKey(default='22d8d0a3-2719-4530-a090-06c11bb47ac7', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
