# Generated by Django 5.2.17 on 2026-09-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_student_date_of_birth_alter_student_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='residence',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
