# Generated by Django 5.2.17 on 2026-09-25 08:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_student_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLineStockAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='inventory.saleline')),
                ('stock_receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='inventory.stockreceiptline')),
            ],
            options={
                'db_table': 'sale_line_stock_allocations',
                'ordering': ['created_at'],
            },
        ),
    ]
